#!/bin/bash

usage()
{
    echo "usage: `basename $0` <module> <case> [param1 [param2 ...]]"
}

if [ $# -lt 2 ]; then
    usage
    exit
fi

MODULE=$1
CASE=$2

FUNC_NAME="g_main"
NAMESPACE="${MODULE}_$CASE"
DECLARE="namespace $NAMESPACE { int $FUNC_NAME(int, char**); } "
MAIN="int main(int argc, char** argv) { return $NAMESPACE::$FUNC_NAME(argc, argv); }"
EXEC=$CASE.run
SRC=$CASE.cpp
INC="-I. -I`pwd`"
GR_LIB="`pwd`/common/gragon.a"


if [ ! -e common/gragon.a ]; then
    cd common
    ./gar
    cd ..
fi

cd $MODULE
echo "$DECLARE $MAIN" > main.cpp
(g++ $INC -o $EXEC main.cpp $SRC $GR_LIB) && echo "Build success, use grun to show it"
