#!/bin/bash

usage()
{
    echo "usage: `basename $0` <module> <case> [param1 [param2 ...]]"
}

if [ $# -lt 2 ]; then
    usage
    exit
fi

MODULE=$1
CASE=$2

EXEC=$CASE.run
INPUT=$CASE.input

cd $MODULE
if [ -e $EXEC ]; then
    shift; shift;
    if [ -e $INPUT ]; then
        cat $INPUT | ./$EXEC $@
    else
        ./$EXEC $@
    fi
else
    echo "NO $EXEC found, please use gbuild to make it"
fi
